export const journalCopy = {
  en: {
    title: "These experiences stay yours.",
    subtitle: "A private place for the moments you want to keep.",
    add: "Add Memory",
    empty: "No memories yet",
    photos: "Photos",
    addPhotos: "Add photos",
    remove: "Remove",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    done: "Done",
    delete: "Delete Memory",
    confirmDelete: "Delete this Memory and its photos? This cannot be undone.",
    note: "Journal",
    noteHint: "Write something about today…",
    moods: "Moods",
    addMood: "Add mood",
    titleLabel: "Activity title",
    date: "Experience date",
    activity: "From a myDate activity",
    freeform: "Something we already did",
    prompt: "Memory Prompt",
    fun: "Fun",
    comfort: "Comfort",
    doAgain: "Would do again",
    overall: "Overall",
    unrated: "Not rated",
    suggested: [
      "🥰 Excited",
      "😌 Comfortable",
      "🤣 Fun",
      "🥹 Emotional",
      "🌙 Peaceful",
      "✨ Special",
    ],
    close: "Close",
    previous: "Previous photo",
    next: "Next photo",
    loading: "Loading…",
    retry: "Retry",
    failed: "Something went wrong. Please try again.",
    missing: "This Memory is unavailable.",
    login: "Sign in",
    signup: "Create account",
    logout: "Sign out",
    username: "Username",
    password: "Password",
    account: "Your private account",
    loginHint: "Sign in to save your memories and photos.",
    verify: "Your account was created. Sign in with your username.",
    authError:
      "Unable to sign in or create the account. Check your username and password.",
    backend:
      "The journal is not available yet. Please try again after setup is complete.",
    private: "Only you can see this Memory.",
    import: "Import local memories",
    importHint:
      "Import this browser’s older memories into your current account. The originals are kept as a backup.",
    importDone: "Local memories imported.",
    importInvalid:
      "Some local records are invalid. Valid memories were imported; the originals are still kept.",
    upload: "Uploading",
    uploadFailed:
      "Some photos could not be uploaded. Retry the failed photos below.",
    pending: "Unfinished upload — remove to free this slot.",
    photo_limit: "A Memory can contain up to 9 photos.",
    photo_large:
      "Choose a photo smaller than 20 MB. If it still fails, export a smaller copy.",
    photo_format:
      "This photo could not be read. Choose a JPEG, PNG or WebP photo.",
    photo_heic:
      "This HEIC photo could not be converted. Export it as JPEG from Photos and try again.",
    optional: "Photos, moods and notes are optional.",
    finish: "Save Memory",
    enrich: "Add photos & note",
    saved: "Memory saved",
    selected: "Choose an activity",
    legacy: "Past activity",
    removeMood: "Remove mood",
    importing: "Importing…",
    signInFirst: "Sign in to keep this experience.",
    photoAlt: "Memory photo",
    accountSwitch: "Your memories are private to this account.",
    importOther:
      "This browser’s local memories were imported into another account. They will not be imported again here.",
  },
  zh: {
    title: "这些经历都属于你。",
    subtitle: "为想记住的时刻，留一处私人的空间。",
    add: "添加回忆",
    empty: "还没有回忆",
    photos: "照片",
    addPhotos: "添加照片",
    remove: "移除",
    edit: "编辑",
    save: "保存",
    cancel: "取消",
    done: "完成",
    delete: "删除回忆",
    confirmDelete: "删除这段回忆及其照片？此操作无法撤销。",
    note: "日记",
    noteHint: "写一点今天的事……",
    moods: "心情",
    addMood: "添加心情",
    titleLabel: "活动标题",
    date: "经历日期",
    activity: "选择 myDate 活动",
    freeform: "我们曾经做过的事",
    prompt: "记忆提示",
    fun: "好玩程度",
    comfort: "舒适程度",
    doAgain: "愿意再体验",
    overall: "整体感受",
    unrated: "未评分",
    suggested: [
      "🥰 兴奋",
      "😌 舒适",
      "🤣 开心",
      "🥹 感动",
      "🌙 平静",
      "✨ 特别",
    ],
    close: "关闭",
    previous: "上一张",
    next: "下一张",
    loading: "加载中……",
    retry: "重试",
    failed: "操作未成功，请重试。",
    missing: "这段回忆暂时无法查看。",
    login: "登录",
    signup: "创建账号",
    logout: "退出登录",
    username: "用户名",
    password: "密码",
    account: "你的私人账号",
    loginHint: "登录后即可保存回忆和照片。",
    verify: "账号已创建，请使用用户名登录。",
    authError: "登录或注册失败，请检查用户名和密码。",
    backend: "回忆日记尚未开放，请完成配置后再试。",
    private: "只有你能查看这段回忆。",
    import: "导入本地回忆",
    importHint: "将此浏览器中的旧回忆导入当前账号，原始数据会保留备份。",
    importDone: "本地回忆已导入。",
    importInvalid: "部分本地记录无效，有效回忆已导入，原始数据仍保留。",
    upload: "正在上传",
    uploadFailed: "部分照片上传失败，可重试下方未成功的照片。",
    pending: "上传未完成，可移除以释放名额。",
    photo_limit: "一次回忆最多可以保存 9 张照片。",
    photo_large: "请选择小于 20 MB 的照片；如仍失败，请导出较小的副本。",
    photo_format: "无法读取这张照片，请选择 JPEG、PNG 或 WebP 照片。",
    photo_heic: "这张 HEIC 照片转换失败，请在相册中导出 JPEG 后重试。",
    optional: "照片、心情和日记都可以不填。",
    finish: "保存回忆",
    enrich: "添加照片和笔记",
    saved: "回忆已保存",
    selected: "选择一个活动",
    legacy: "曾经的活动",
    removeMood: "移除心情",
    importing: "正在导入……",
    signInFirst: "登录后保存这次经历。",
    photoAlt: "回忆照片",
    accountSwitch: "回忆仅属于当前账号。",
    importOther: "此浏览器的旧回忆已导入其他账号，不会再次导入当前账号。",
  },
  ja: {
    title: "この経験は、あなたのもの。",
    subtitle: "残しておきたい瞬間のための、あなただけの場所。",
    add: "思い出を追加",
    empty: "まだ思い出はありません",
    photos: "写真",
    addPhotos: "写真を追加",
    remove: "削除",
    edit: "編集",
    save: "保存",
    cancel: "キャンセル",
    done: "完了",
    delete: "思い出を削除",
    confirmDelete: "この思い出と写真を削除しますか？元に戻せません。",
    note: "日記",
    noteHint: "今日のことを書いてみよう…",
    moods: "気持ち",
    addMood: "気持ちを追加",
    titleLabel: "活動のタイトル",
    date: "体験した日",
    activity: "myDate の活動から",
    freeform: "以前に体験したこと",
    prompt: "思い出のヒント",
    fun: "楽しさ",
    comfort: "心地よさ",
    doAgain: "また体験したい",
    overall: "全体の感想",
    unrated: "評価なし",
    suggested: [
      "🥰 わくわく",
      "😌 心地よい",
      "🤣 楽しい",
      "🥹 感動",
      "🌙 穏やか",
      "✨ 特別",
    ],
    close: "閉じる",
    previous: "前の写真",
    next: "次の写真",
    loading: "読み込み中…",
    retry: "再試行",
    failed: "処理に失敗しました。もう一度お試しください。",
    missing: "この思い出は表示できません。",
    login: "ログイン",
    signup: "アカウント作成",
    logout: "ログアウト",
    username: "ユーザー名",
    password: "パスワード",
    account: "あなただけのアカウント",
    loginHint: "ログインして思い出や写真を保存しましょう。",
    verify: "メールでアカウントを確認してからログインしてください。",
    authError:
      "ログインまたは登録に失敗しました。メールとパスワード、メール認証を確認してください。",
    backend: "日記はまだ利用できません。設定完了後にお試しください。",
    private: "この思い出はあなただけが閲覧できます。",
    import: "ローカルの思い出を取り込む",
    importHint:
      "このブラウザの以前の思い出を現在のアカウントに取り込みます。元のデータは保管します。",
    importDone: "思い出を取り込みました。",
    importInvalid:
      "一部のデータが無効です。有効な思い出を取り込み、元のデータは保管しています。",
    upload: "アップロード中",
    uploadFailed:
      "一部の写真をアップロードできませんでした。失敗した写真を再試行できます。",
    pending: "未完了のアップロードです。削除して空きを確保できます。",
    photo_limit: "1つの思い出に保存できる写真は最大9枚です。",
    photo_large:
      "20 MB 以下の写真を選んでください。失敗する場合は小さい画像を書き出してください。",
    photo_format: "写真を読み込めません。JPEG、PNG、WebP を選んでください。",
    photo_heic:
      "HEIC 写真を変換できませんでした。写真アプリから JPEG に書き出して再試行してください。",
    optional: "写真、気持ち、日記は任意です。",
    finish: "思い出を保存",
    enrich: "写真や日記を追加",
    saved: "思い出を保存しました",
    selected: "活動を選択",
    legacy: "過去の活動",
    removeMood: "気持ちを削除",
    importing: "取り込み中…",
    signInFirst: "ログインしてこの経験を残しましょう。",
    photoAlt: "思い出の写真",
    accountSwitch: "思い出は現在のアカウントだけのものです。",
    importOther:
      "このブラウザの思い出は別のアカウントに取り込み済みです。再取り込みはしません。",
  },
} as const;
